services:
  - type: web
    name: frontend  # Puedes darle un nombre a tu servicio de frontend
    buildCommand: npm run build
    staticPublishPath: /app/build
    routes:
      - type: rewrite
        source: '/*'
        destination: /index.html